//------------STUDENT------------
//Show students
get http://localhost:8000/api/funcionario

####
//Show student by id
get http://localhost:8000/api/funcionario/6

####
//Edit student
put http://localhost:8000/api/funcionario/5
Content-Type: application/json

{
    "nome": "Alterei o funcionario kaka",
    "cpf": "",
    "rg": "",
    "idade": "",
    "email": "",
    "endereco": "",
    "telefoneCelular": ""
}

####
//Create student
post http://localhost:8000/api/funcionario
Content-type: application/json

{
    "nome": "Criei o funcionario kaka",
    "cpf": "",
    "rg": "",
    "idade": "",
    "email": "",
    "endereco": "",
    "telefoneCelular": ""
}

####
//Delete student
delete http://localhost:8000/api/funcionario/6
####


//------------TEACHER------------
//Show teachers
get http://localhost:8000/api/peca


####
//Show teacher by id
get http://localhost:8000/api/peca/1

####
//Edit teacher
put http://localhost:8000/api/peca/1
Content-Type: application/json

{
    "nome": "Alterei o proff kaka",
    "idade": "",
    "grauGraduacao": "",
    "email": "",
    "endereco": "",
    "telefoneCelular": ""
}

####
//Create teacher
post http://localhost:8000/api/peca
Content-Type: application/json

{
    "nome": "Criei um proff kaka",
    "idade": "",
    "grauGraduacao": "",
    "email": "",
    "endereco": "",
    "telefoneCelular": ""
}

####
//Delete teacher
delete http://localhost:8000/api/peca/2
####


//------------CLASS------------
//Show classes
get http://localhost:8000/api/carros

####
//Show class by id
get http://localhost:8000/api/carros/1

####
//Edit class
put http://localhost:8000/api/carros/1
Content-Type: application/json

{
    "curso": "Mudei kaka",
    "semestre": "",
    "turno": "",
    "funcionario": ""
}

####
//Create class
post http://localhost:8000/api/carros
Content-Type: application/json

{
    "curso": "Teste",
    "semestre": "",
    "turno": "",
    "funcionario": ""
}

####
//Delete class
delete http://localhost:8000/api/carros/4
